config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { registrations: 'registrations' }
    
  root 'pages#home'
  
  get '/users/:id', to: 'users#show', as: 'user'
  resources :boards
  resources :comments, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :bigint           not null, primary key
#  body       :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Board < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 1000 }
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  comment    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_comments_on_board_id  (board_id)
#  index_comments_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (board_id => boards.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :board
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string           default(""), not null
#  profile_photo          :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates :name, presence: true, length: { maximum: 20}
  
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: %i[show new create edit update destroy]
  before_action :set_target_board, only: %i[show edit update destroy]
  
  def index
    @board = Board.page(params[:page]).order(created_at: :desc)
  end

  def show
    @comment = Comment.new(board_id: @board.id)
    @comments = Comment.all
  end

  def new
    @board = Board.new
  end
  
  def create
    @board = Board.new(board_params)
    if @board.save
      flash[:notice] = "投稿に成功しました"
      redirect_to @board
    else
      render new_board_path
    end
  end

  def edit
  end
  
  def update
    @board.update(board_params)
    if @board.save
      flash[:notice] = "「#{ @board.title }」を更新しました"
      redirect_to @board
    else
      render :edit
    end
  end
  
  def destroy
    @board.delete
    flash[:alert] = "投稿を削除しました"
    redirect_to boards_path
  end
  
  private
  
    def board_params
      params.require(:board).permit(:title, :body).merge(user_id: current_user.id)
    end
    
    def set_target_board
      @board = Board.find_by(id: params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.board_id = current_user.id
    if @comment.save
      flash[:notice] = "コメントしました"
      redirect_back fallback_location: root_path
    else
      redirect_back fallback_location: root_path
    end
  end

  def destroy
    comment = Comment.find_by(id: params[:id])
    comment.delete
    flash[:notice] = "コメントが削除されました"
    redirect_to comment.board
  end
  
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
  
  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_comment_form.html.erb
<div class="p-comment__formBox">
  <p class="p-comment__formTitle">コメント記入</p>
  <%= form_for comment do |f| %>
    <%= f.hidden_field :board_id %>
    <div class="form-group">
      <%= f.label :comment, 'コメント' %>
      <%= f.text_area :comment, class: 'form-control', rows: 4 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
  <h1>節約術編集</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to '詳細', @board, class: 'btn btn-outline-dark' %>
    <%= link_to '削除', @board, method: :delete, class: 'btn btn-outline-dark', data: { confirm: '投稿を削除しますか？' } %>
  </div>
</div>
<%= form_for @board do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
  </div>
  <%= f.submit '更新', class: 'btn btn-primary' %>
<% end %>

app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>みんなの節約術</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to "新規作成", new_board_path, class: "btn btn-outline-dark" %>
  </div>
</div>
<table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>タイトル</th>
      <th>投稿者</th>
      <th>投稿日</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @board.each do |board| %>
    <tr>
      <td><%= board.title %></td>
      <td><%= board.user.name %></td>
      <td><%= board.created_at.to_s(:datetime_jp) %></td>
      <td><%= link_to "詳細", board, class: "btn btn-outline-dark" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @board %>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板作成</h1>
  <div class="ml-auto boards__linkBox">
    <%= link_to "みんなの節約術", boards_path, class: "btn btn-outline-dark" %>
  </div>
</div>
<%= form_for @board do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="form-group">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body, "本文" %>
    <%= f.text_area :body, class: "form-control", rows: 10 %>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
<% end %>

app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
  <div class="ml-auto boards__linkBox">
    <%= link_to "みんなの節約術", boards_path, class: "btn btn-outline-dark" %>
    <%= link_to "編集", edit_board_path, class: "btn btn-outline-dark" %>
  </div>
</div>

<!--掲示板詳細表示部分-->
<div class="card">
  <div class="card-header">
    <h4><%= @board.title %></h4>
  </div>
    <div class="card-body">
      <p class="card-text"><%= simple_format(@board.body) %></p>
      <p class="text-right font-weight-bold mr-10"><%= @board.user.name %></p>
    </div>
</div>

<!--コメント送信部分-->
<%= render partial: 'comments/form', locals: { comment: @comment } %>

<!--コメント表示部分-->
<div class="p-comment__list">
  <div class="p-comment__listTitle">コメント</div>
  <!--コメント繰り返し部分-->
  <% @comments.each do |comment| %>
    <div class="p-comment__item">
      <p><%= simple_format(comment.comment) %></p>
      <div class="p-comment__bottomLine">
        <% if current_user.id == comment.user_id %>
          <span><%= link_to '削除', comment, method: :delete, data: { confirm: '削除してよろしいですか？' }, class: "btn btn-outline-dark" %></span>
        <% end %>
        <span><%= comment.created_at.to_s(:datetime_jp) %></span>
        <span><%= comment.user.name %></span>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div class="p-comment__item">
  <p><%= simple_format(comment.comment) %></p>
  <div class="p-comment__bottomLine">
    <span><%= comment.created_at.to_s(:datetime_jp) %></span>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="p-comment__formBox">
  <p class="p-comment__formTitle">コメント記入</p>
  <%= form_for comment do |f| %>
    <%= f.hidden_field :board_id %>
    <div class="form-group">
      <%= f.label :comment, 'コメント' %>
      <%= f.text_area :comment, class: 'form-control', rows: 4 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManeManey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <%= render 'shared/header' %>
      <%= render 'shared/flash' %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>ホームページ</h1>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<!--flashの記述-->
<% if flash[:notice] %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        Copyright © ManeManey
      </p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "ManeManey", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'みんなの節約術', boards_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to '投稿する', new_board_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ユーザー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% if user_signed_in? %>
          <%= link_to "マイページ", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% else %>
          <%= link_to "ユーザー登録", new_user_registration_path, class: "dropdown-item" %>
          <%= link_to "ログイン", new_user_session_path, class: "dropdown-item" %>
        <% end %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row bg-white">
    <div class="col-md-4 text-center">
      <%= image_tag avatar_url(@user), class: "round-img" %>
    </div>
    <div class="col-md-8 pt-15">
      <div class="row">
        <h2><%= @user.name %></h2>
        <% if @user == current_user %>
          <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
          <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
        <% end %>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="list-group text-center">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if @user == current_user %>
        <div class="row">
          <p>
            <%= @user.email %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>